### ISSUE TITLE
Net.Fluentmigrator "Exists" extensions fail in SQL Server when the object exists

### ISSUE THREAD

**Issue by MikeC99** [zidad/net-tools#5]
When running in SQL Server, Method Net.FluentMigrator.DataExpressionRoot.Exists fails when calling Fluentmigrator processor with a command "SELECT * FROM ..." because the processor attempts to convert the result to Int32. When object exists, the return value is rarely a valid string and throws exception "Input string was not in a correct format.".

Solution: change "SELECT * "  to "SELECT COUNT(*) "

**Comment by MikeC99** [comment]
Alternatively, "SELECT 1 " works also

**Comment by zidad** [comment]
Hi Mike, 

Thanks a lot for reporting! I've implemented your fix...

**Comment by zidad** [comment]
and updated the nuget package https://www.nuget.org/packages/net.fluentmigrator
